### PR TITLE
Update jasmine-core to 1.2 including HtmlReporting

### PR DESCRIPTION
**Pull request by dimroc**
This updates all jasmine-core dependencies (jasmine.js, jasmine-html.js, jasmine.css) and switches the reporter from the old TrivialReporter to the new HtmlReporter that's standard in jasmine 1.2.

### CODE REVIEW

**Comment by bradphelan** [comment]
Hey I can't auto merge this probably because of a recent other pull request I did. Can you fix this up so I can do an auto merge. Thanks

**Comment by dimroc** [comment]
The pull request has been updated to include all upstream changes.

**Comment by alekseykulikov** [comment]
+1

**Comment by bradphelan** [comment]
Thanks for the contribution

**Pull request merged**
