### PR TITLE
Rails 4 routing

### PR DESCRIPTION
**Pull request by kstevens715**
This is a small fix to provide compatibility with Rails 4. I'm using `get` instead of `match`, as the routes should only accept GET requests, I believe. Thanks and thanks to @leifg as well.

### CODE REVIEW

**Comment by jejacks0n** [comment]
As far as I'm aware this is the only change needed.  Are all the assets from the engine loading correctly?  I had issues with that (https://github.com/rails/rails/pull/8712)

**Comment by kstevens715** [comment]
Yes, the assets appear fine. I only have an extremely basic test suite I'm using it with right now, but it works fine. This is the only change needed as far as I know too.

**Comment by jejacks0n** [comment]
Thanks!  I'll be merging this in shortly. =)

**Comment by kstevens715** [comment]
Thank you for merging so fast!

**Comment by jejacks0n** [comment]
It's what I'm doing with my day. =)

**Pull request merged**
