### PR TITLE
Remove the haml requirement from jasminerice.

### PR DESCRIPTION
**Pull request by eventualbuddha**
Pulling in haml just for the index file was causing issues with an alpha version of sass (it repeatedly printed a warning when loading the Rails environment). Seeing as how haml was used for such a small thing it seemed better to simply remove it from jasminerice.

### CODE REVIEW

**Comment by bradphelan** [comment]
Sorry I won't pull this. I use HAML for all my projects. A **warning** when using an alpha version of another gem is not really a reason to patch here.

**Comment by eventualbuddha** [comment]
haml really ought to be fixed, I agree, since it's the one that has the [dubious sass version checking mechanism](https://github.com/nex3/haml/blob/master/lib/haml/util.rb#L352-355) that's causing the problem in the first place. I wouldn't have bothered with this patch if jasminerice had made extensive use of haml, but considering it was so tiny I figured it wouldn't matter. Thanks anyway.

**Comment by christiannelson** [comment]
@bradphelan Any chance you reconsider this, but for a different reason? Every project that uses jasmine-rice -- which is quite a few, it's good stuff -- end up depending on haml (weighing in at 370k+) whether they use it or not. We no longer use haml (in favor of slim), but haml ends up being installed and loaded anyway. Lots of gems include things that either aren't really critical for the normal operation of the gem (not this case) or they use something for a thin sliver of functionality (this case).

The end result is that a simple rails project bloats up to 50+ gems (directly and transitively), with some deps not really being necessary (because they're there to support obscure features) or they're included to and barely used.

This bloat is giving rails and the rails community a bad rep, which is unfortunate.

**Comment by nick-desteffen** [comment]
I agree, I just installed Jasminerice and gagged a bit when I saw it needed Haml.  Adding Haml "saves" 3 lines of markup code.  It's overkill for something like this.

**Pull request closed without merging**
