### PR TITLE
Not having the haml gem loaded prevents rails from finding spec/index.html.haml

### PR DESCRIPTION
**Pull request by justinbarry**
Haml is needed in the parent app to render engine views. Thought it should be called out explicitly for those who don't have haml installed.

### CODE REVIEW

**Comment by netzpirat** [comment]
This shouldn't be necessary, because the `haml` gem is declared as dependency of the `jasminerice` gem and should be  installed automatically: https://rubygems.org/gems/jasminerice

**Comment by justinbarry** [comment]
For whatever reason I had to add it explicitly. Any thought as to why? Haml is listed in Gemfile.lock.

**Comment by netzpirat** [comment]
When `haml` is in your `Gemfile.lock`, then the Jasminerice dependencies are properly recognized. So I guess it's something with Bundler in your setup.

**Comment by bradphelan** [comment]
I added as a gemspec dependency myself on a commit that was sitting on me dev machine so this pull request is no longer needed

See https://github.com/bradphelan/jasminerice/commit/177acb9c759602f4293bd1f867af1e425690e611

**Pull request closed without merging**
