### PR TITLE
Small change to readme

### PR DESCRIPTION
**Pull request by dtuite**
Hi, first thanks for making this gem, I tried to make jasmine work with 3.1 myself the other day and wanted to jump out the window.

When I followed your install instructions I got a `ReferenceError: "$ is not defined"`. Basically because the file `/assets/jasmine-jquery-1.2.0.js` requires jQuery to be loaded before it can work (I think).

Anyway adding a sprockets directive for jquery solves the problem.

This is my first ever pull request so my apologies if I'm doing something wrong!

Dave

### CODE REVIEW

**Comment by dtuite** [comment]
Actually, now that I think about it, this change is pretty silly because we have to `#= require application` anyway to load our compiled javascript file. It might be better to put that line in instead?

**Comment by bradphelan** [comment]
You are right. But I would not put it in application.js but in 

https://github.com/bradphelan/jasminerice/blob/master/app/assets/javascripts/jasminerice.js.coffee

give that a go and if it works for me send me a pull request

**Comment by dtuite** [comment]
Just a thought though, if I have a `#= require jquery` in jasminerice.js.coffee and someone creates a new rails project using prototype as the JS library, sprockets is going to throw an exception when if can't find jQuery right? I'm likely causing a bigger problem then I'm solving.

**Comment by bradphelan** [comment]
Yes I think you are right. Probably better to just include #=requirey jquery
when you need it.

**Pull request closed without merging**
